name: Test
on:
  push: { branches: [ "main" ] }
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.remote-data == 'remote' }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python: ["3.9", "3.10", "3.11"]
        remote-data: [""]
        include:
        - os: "ubuntu-latest"
          python: "3.11"
          # This leg of the tests runs doctests against the data that is
          # currently available on echemdb.org. This test might fail
          # when substantial changes have been introduced
          # with this run that have not been published on echemdb.org yet.
          remote-data: 'remote'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with: { submodules: recursive }
      - name: setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "${{ matrix.python }}"
          miniforge-variant: Mambaforge
      - name: install dependencies
        shell: bash -l {0}
        run: |
          mamba env update --quiet -n test -f environment.yml
          conda list
      - name: install unitpackage
        shell: bash -l {0}
        run: |
          pip install -e .
      - name: doctest
        shell: bash -l {0}
        run: |
          pytest -n auto --doctest-plus ${{ matrix.remote-data == 'remote' && '--remote-data' || '' }} --doctest-modules unitpackage
